[workspace]
members = ["musics", "sound"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
camino = { version = "1.1.2", features = ["serde1"] }