[package]
name = "musics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sound = { path = "../sound" }

eframe = "0.20.1"
camino.workspace = true
slotmap = "1.0.6"